platform :ios, '8.0'


target 'AshotTestApp' do
  use_frameworks!
  # Pods for AshotTestApp

  target 'AshotTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AshotTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
